version: 2
jobs:
  build:
    #docker:
    #  - image: mcr.microsoft.com/dotnet/sdk:3.1
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Test.CICDFlow
      - run: 
          command: |
             docker info
             docker build -t aspnetapp -f Dockerfile .
