version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Test.CICDFlow
      - run: |
         docker info
         docker build -t aspnetapp -f Dockerfile .
