version: 2
orbs:
  build-tools: circleci/build-tools@2.9.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Test.CICDFlow
      - run:
          name: Build for Release
          command: |
            dotnet publish ./Test.CICDFlow/Test.CICDFlow.csproj -c Release -p:UseAppHost=false -o ../app-publish
            cd ../app-publish
