version: 2
orbs:
  build-tools: circleci/build-tools@2.9.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
      - image: circleci/php:7.2-node-browsers
    working_directory: /tmp
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Test.CICDFlow
      - run:
          name: Build for Release
          command: |
            dotnet publish ./Test.CICDFlow/Test.CICDFlow.csproj -c Release -p:UseAppHost=false -o ../app-publish
            cd ../app-publish
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
deploy:
    docker:
      - image: mcr.microsoft.com/azure-cli:latest
    environment:
      VERSION_NUMBER: 0.0.0.1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Azure Staging Deploy
          command: |
            cd /tmp/workspace
            ls -l
